### ISSUE TITLE
每小时tail新的日志文件是否可行？

### ISSUE THREAD

**Issue by duanyixuan** [ningg/flume-ng-extends-source#11]
嗨，你好。目前，我们公司的日志是按照小时进行切分的，spoolDir指向这些文件所在文件夹，是否可以？我在线下测试结果：初始状态为只有2016081718.log；当日19点后有新文件2016081719.log生成后，2016081718.log的文件才被标记为COMPLETED;然后，监控文件转向2016081719.log；貌似功能可以的。求正解

**Comment by MC17** [comment]
您好，能否发给我一份编译好的jar包，我按照步骤编译jar包并放在lib文件夹后启动flume agent时出现了问题，不胜感激

**Comment by ningg** [comment]
出现这个情况，也出乎我的意料，你多测试一下，如果能用，你就用吧

**Comment by duanyixuan** [comment]
我看了您的源码，读后感为：您这个source是个单线程串行读取文件的逻辑，targetFilename改为yyyyMMddHH，确实可以实现小时切换targetFile的功能，正在线上适用中，有啥问题有急事找您求解的，谢啦

**Comment by feloxx** [comment]
@duanyixuan 哥们,你们最后按小时分割的采集测试的怎么样了呢
我们最近也有这样的需求

**Comment by duanyixuan** [comment]
从去年上线一直跑到现在，如果收集的不是nginx等的日志，而是自己写日志，要注意避免EOFExcepition
