### ISSUE TITLE
当日日志文件追加无法实时收集

### ISSUE THREAD

**Issue by yanghua** [ningg/flume-ng-extends-source#2]
在flume-ng agent启动起来后对当日文件进行收集时，当日文件里新增新的日志后，新增的日志无法被收集。然后关闭agent，再次启动，新增的日志才可以被agent收集。请问，这种情况大概是哪里出了问题？

**Comment by ningg** [comment]
我还没有遇到这个现象，猜测原因：
1. `当日文件`是每天新建的新的文件吗？还是原始文件重命名的？RE：默认要求是每日新建一个文件；
2. 针对`当日文件`收集新增日志的基本原理：在文件末尾，设定一个指针，如果追加更新，则能够被收集走，如果是在文件上覆盖前文内容进行的覆盖更新，则无法收集走；
3. 如果再次出现你遇到的现象，可以删除`当日文件`所在目录的`.flumespooltail`文件夹，这里保存着指向文件末尾的指针，删除之后，再试试。

**Comment by yanghua** [comment]
我今天又再次测试了一遍，新建一个当日日期的日志文件。然后将agent开启，在当日日志文件内添加内容，新内容并没有发送到sink里。但我通过一些修改可以进行追加收集。修改是通过将这句：
https://github.com/ningg/flume-ng-extends-source/blob/master/src%2Fmain%2Fjava%2Fcom%2Fgithub%2Fningg%2Fflume%2Fsource%2FReliableSpoolDirectoryTailFileEventReader.java#L241

移动到这个if判断之后，在外面执行：

```
currentFile = getNextFile();
```

这样就是可以收集到当日文件里追加的新日志。个人猜测主要是因为追加日志后，指针位置没有更新造成的。而修改后的代码，每次都调 `getNextFile();` 产生的效果为：
- 对于有历史日志文件存在，它就是获取下一个历史日志文件。（这个跟你放在if中的逻辑相同）
- 而对于只剩下当日文件，这个方法起到的作用是刷新当日文件，重新构建追加日志后的新文件的流

因为，在我没修改代码之前，用你的代码，再重启agent后，新追加的日志可以被收集到，所以我才猜测是：当只剩下当日文件时，currentFile引用的对象是旧的当日日志文件的对象。另外，这也印证了原来的SpoolDirSource的特征之一：它不支持对正在收集的日志进行更改。这个特征是符合我现在的现象的。而我浏览了你的源码之后，也没发现你有针对这个特征的修改。（或者是你怎么处理的，我没理解）？
总的来说，我觉得问题出在，当currentFile代表了当日文件之后，它的`file`以及`desrializer`等信息是它针对当日文件第一次初始化时的快照，当有新的日志追加进来之后，它不是引用当日日志文件的最新版本，所以，那个指针无法识别出新日志进来。而getNextFile();对于只剩下当日文件没收集时，相当于起到刷新当日文件的作用，所以起到了效果。

我针对我这边的问题发表了看法，也可能存在误打误撞的情况，或者currentFile本来就不需要刷新，它就能意识到当日文件又有新的日志追加进来了？
还是我这种手动测试存在问题？请问你真的在线上用了没有问题么？

**Comment by ningg** [comment]
我当前的理解：
1. currentFile本来就不需要刷新，它就能意识到当日文件又有新的日志追加进来了？
   - 是的，currentFile本来就不需要刷新，就能获取获取当日追加更新的内容；
2. 还是我这种手动测试存在问题？请问你真的在线上用了没有问题么？
   - 是的，在线上用了，有一段时间了，没有问题；

你在Windows下部署的Flume Agent？还是Linux下，可以把你的具体场景描述的更详细一点：
- 什么OS环境？
- 什么JRE？
- 什么日志？

**Comment by ningg** [comment]
我今天又再次测试了一遍，新建一个当日日期的日志文件。然后将agent开启，....

试试：先启动`Flume agent`，然后，再新建`当日日期的日志文件`

**Comment by ningg** [comment]
> 另外，这也印证了原来的SpoolDirSource的特征之一：它不支持对正在收集的日志进行更改。这个特征是符合我现在的现象的。而我浏览了你的源码之后，也没发现你有针对这个特征的修改。（或者是你怎么处理的，我没理解）？

RE: 代码L339~L344，针对 `SpoolDirSource的特征之一：它不支持对正在收集的日志进行更改` 进行修改：

修改之前：

```
// Verify that spooling assumptions hold
if (fileToRoll.lastModified() != currentFile.get().getLastModified()) {
  String message = "File has been modified since being read: " + fileToRoll;
  throw new IllegalStateException(message);
}
if (fileToRoll.length() != currentFile.get().getLength()) {
  String message = "File has changed size since being read: " + fileToRoll;
  throw new IllegalStateException(message);
}
```

修改之后：

```
        // Verify that spooling assumptions hold
    if (fileToRoll.lastModified() == currentFile.get().getLastModified()) {
      logger.info("File:{} has not been modified since being read.", fileToRoll.getName());
    }
    if (fileToRoll.length() == currentFile.get().getLength()) {
      logger.info("File:{} has not changed size since being read.", fileToRoll.getName());
    }
```

修改之前代码（链接）：
https://github.com/apache/flume/blob/4d2a34e931554baa1c1b255d95540a46354a521f/flume-ng-core/src/main/java/org/apache/flume/client/avro/ReliableSpoolingFileEventReader.java#L319

修改之后代码（链接）：

https://github.com/ningg/flume-ng-extends-source/blob/master/src%2Fmain%2Fjava%2Fcom%2Fgithub%2Fningg%2Fflume%2Fsource%2FReliableSpoolDirectoryTailFileEventReader.java#L339

**Comment by yanghua** [comment]
你好，经过测试，你的代码确实没问题，是我测试方式的问题。我之前是直接用文本编辑器打开当日日志文件，然后往里面输入新内容来测试当日日志的追加内容功能的。今天，我改用log4j写日志是可以实时追加的，但到目前为止，用文本编辑器打开手动写入还是没有办法追加，而我改了之前说的那句代码就可以。
我的环境：

```
操作系统：mac os x 10.10.3 
JDK : 1.7.0_45
日志就是普通的程序日志
```

不过可以确定的是，你的代码没有问题。谢谢。

**Comment by ningg** [comment]
不客气，相互学习~

**Comment by rarewei** [comment]
如果自行测试话, 在启动flume agent后, 如何创建文件才能生效?.  我使用touch和echo xxx >> 2016-01-01.log的方式, 均不能触发source到sink..
